apiVersion: v1
kind: Pod
metadata:
  name: cpustress-1
  namespace: newalmaden-nick
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  containers:
    - name: cpustress
      image: containerstack/cpustress
      tty: true
      args: ["--cpu=4", "--vm-bytes=200M", "#test-1"]
      resources:
        limits:
          cpu: 4000m
          memory: 300M
        requests:
          cpu: 1000m
          memory: 300M
  nodeSelector:
    kubernetes.io/hostname: "node.internal"